---
# SQL
#
# table - The database table name, in snake_case
# object: The object name, in PascalCase
sql:
  table: table_name
  object: Obj

configs:
  - signature: SQLDataSourceName() (dsn string)
    description: SQLDataSourceName is the connections string to the SQL data source.
    secret: true

functions:
  - signature: Create(obj *Obj) (objKey ObjKey)
    description: Create creates a new object, returning its key.
  - signature: Store(obj *Obj) (stored bool)
    description: Store updates the object.
  - signature: MustStore(obj *Obj)
    description: MustStore updates the object.
  - signature: Revise(obj *Obj) (revised bool)
    description: Revise updates the object only if the revision matches.
  - signature: MustRevise(obj *Obj)
    description: MustRevise updates the object only if the revision matches.
  - signature: Delete(objKey ObjKey) (deleted bool)
    description: Delete deletes the object.
  - signature: MustDelete(objKey ObjKey)
    description: MustDelete deletes the object.
  - signature: List(query Query) (objs []*Obj, totalCount int)
    description: List returns the objects matching the query, and the total count of matches regardless of the limit.
  - signature: Lookup(query Query) (obj *Obj, found bool)
    description: Lookup returns the single object matching the query. It errors if more than one object matches the query.
  - signature: MustLookup(query Query) (obj *Obj)
    description: MustLookup returns the single object matching the query. It errors unless exactly one object matches the query.
  - signature: Load(objKey ObjKey) (obj *Obj, found bool)
    description: Load returns the object associated with the key.
  - signature: MustLoad(objKey ObjKey) (obj *Obj)
    description: MustLoad returns the object associated with the key. It errors if the object is not found.
  - signature: BulkLoad(objKeys []ObjKey) (objs []*Obj)
    description: BulkLoad returns the objects matching the keys.
  - signature: BulkDelete(objKeys []ObjKey) (deletedKeys []ObjKey)
    description: BulkDelete deletes the objects matching the keys, returning the keys of the deleted objects.
  - signature: BulkCreate(objs []*Obj) (objKeys []ObjKey)
    description: BulkCreate creates multiple objects, returning their keys.
  - signature: BulkStore(objs []*Obj) (storedKeys []ObjKey)
    description: BulkStore updates multiple objects, returning the keys of the stored objects.
  - signature: BulkRevise(objs []*Obj) (revisedKeys []ObjKey)
    description: BulkRevise updates multiple objects only if the revision matches, returning the keys of the revised objects.
  - signature: Purge(query Query) (deletedKeys []ObjKey)
    description: Purge deletes all objects matching the query, returning the keys of the deleted objects.
  - signature: Count(query Query) (count int)
    description: Count returns the number of objects matching the query, disregarding pagination.
